version: "3.9"

services:
  worker:
    build: .
    command: celery -A app.celery_app worker -l info
    depends_on:
      - db
    env_file:
      - .env.local
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/app_db
    networks:
      - default
      - more_platform

  beat:
    build: .
    command: celery -A app.celery_app beat -l info
    depends_on:
      - db
    env_file:
      - .env.local
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/app_db
    networks:
      - default
      - more_platform

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  default: {}
  more_platform:
    external: true
    name: traefik_default
